# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provider 'virtualbox' do |vbox|
        vbox.memory = 1024

        vbox.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
        vbox.customize ['modifyvm', :id, '--ioapic', 'on']
        vbox.customize ['modifyvm', :id, '--cpus', '2']
    end

    config.vm.define :php54 do |php54|
        php54.vm.box = 'jubianchi/php-54'
    end

    config.vm.define :php55 do |php55|
        php55.vm.box = 'jubianchi/php-55'
    end

    config.vm.define :php56 do |php56|
        php56.vm.box = 'jubianchi/php-56'
    end

    config.vm.provision :shell, inline: 'echo \'phar.readonly = Off\' | sudo tee /etc/php5/conf.d/phar.ini'
    config.vm.provision :shell, inline: 'sudo composer self-update'

    config.vm.provision :shell, inline: 'sudo -u vagrant -H composer global require atoum/atoum dev-master'
    config.vm.provision :shell, inline: 'sudo -u vagrant -H composer global require phpunit/phpunit *@stable'
    config.vm.provision :shell, inline: 'sudo -u vagrant -H composer global require pdepend/pdepend  *@stable'
    config.vm.provision :shell, inline: 'sudo -u vagrant -H composer global require phpmd/phpmd  *@stable'
    config.vm.provision :shell, inline: 'sudo -u vagrant -H composer global update'

    config.vm.provision :shell, inline: '( which php-cs-fixer && sudo php-cs-fixer self-update ) || sudo wget -O /usr/local/bin/php-cs-fixer http://cs.sensiolabs.org/get/php-cs-fixer.phar && sudo chmod +x /usr/local/bin/php-cs-fixer'

    config.vm.provision :shell, inline: '( cat /etc/profile | grep -q \'composer/vendor/bin\' ) || ( echo \'export PATH=$PATH:~/.composer/vendor/bin\' | sudo tee -a /etc/profile )'
end
