Vagrant.configure(2) do |config|
    config.vm.box = 'debian-wheezy-chef'

    archs = %w(i386 amd64)
    providers = %w(vbox vmware)

    archs.each do |arch|
        providers.each do |provider|
            config.vm.define :"#{arch}-#{provider}" do |box|
                box.vm.box_url = "debian-wheezy-chef-#{arch}-#{provider}-1.0.0.box"
            end
        end
    end
end
