Vagrant.configure(2) do |config|
    config.vm.box = 'centos-65-chef'

    archs = %w(i386 amd64)
    providers = %w(vbox vmware)

    archs.each do |arch|
        providers.each do |provider|
            config.vm.define :"#{arch}-#{provider}" do |i386|
                i386.vm.box_url = "centos-65-chef-#{arch}-#{provider}-1.0.0.box"
            end
        end
    end
end
